config/routes.rb
Rails.application.routes.draw do
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task

  post 'tasks', to: 'tasks#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    Task.create!(task_params)
    redirect_to tasks_path
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
  end

  def destroy
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

private
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<h1>Task#create</h1>
<p>Find me in app/views/task/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Task#destroy</h1>
<p>Find me in app/views/task/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= form_for(@task) do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: "labels" %>
</div>

<div class="form-group">
  <%= f.label :details %>
  <%= f.text_field :details, class: "labels" %>
</div>
<%= f.check_box :completed%> Completed
<div class="button_update">
  <%= f.submit 'Update Task', class: "btn" %>
</div>
<% end %>

<hr>

<div class="retour">
  <%= link_to "Back to list", tasks_path(@task)%>
</div>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
  <ol>
<% @tasks.each do |task|%>
<li>
<% if task.completed%>
<img src="https://img.icons8.com/ios/30/000000/checked-checkbox.png">
<% else%>
<img src="https://img.icons8.com/ios/30/000000/unchecked-checkbox.png">
<% end%>
<%= link_to task.title, task_path(task)%>
</li>
<% end%>
 </ol>
<hr>
 <div class="add_new">
 <img src="https://img.icons8.com/office/16/000000/plus-math.png"><%= link_to "Add a new task", tasks_new_path(@task)%>
 </div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_for(@task) do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: "labels" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :details %>
  <%= f.text_field :details, class: "labels" %>
  </div>
</div>

  <%= f.submit 'Create Task', class: "btn" %>
<% end %>

<hr>

<div class="retour">
  <%= link_to "Back to list", tasks_path(@task)%>
</div>

app/views/tasks/show.html.erb
<h1><%= @task.title%></h1>

<div class="edit-task">
<img src="https://img.icons8.com/ios/50/000000/pencil-tip.png"><%= link_to "Edit this task", edit_path(@task)%>
</div>


<div class="details">
<h2><%= @task.details%></h2>
</div>

<% if @task.completed%>
<img src="https://img.icons8.com/ios/30/000000/checked-checkbox.png">This task is completed
<% else%>
<img src="https://img.icons8.com/ios/30/000000/unchecked-checkbox.png">This task is not completed yet
<% end%>

<div class="retour">
  <%= link_to "Back to list", tasks_path(@task)%>
</div>